---
- name: Bootstrap ingress + cert-manager + external-dns (portfolio code only)
  hosts: local
  gather_facts: false
  vars:
    kubeconfig: "{{ kubeconfig | default(lookup('env','KUBECONFIG') | default(lookup('env','HOME') + '/.kube/config', true)) }}"
  tasks:
    - name: Install NGINX ingress via Helm
      ansible.builtin.import_role:
        name: cluster-bootstrap

    - name: Install cert-manager + ClusterIssuer
      ansible.builtin.import_role:
        name: cert-manager

    - name: Install external-dns (Azure DNS)
      ansible.builtin.import_role:
        name: external-dns
